stages:
  - test

junit:
  stage: test
  image: "maven:3"
  tags: 
    - BP-TDGT-CI
  script:
    - mvn test

spotbugs:
  stage: test
  image: "maven:3"
  tags:
    - BP-TDGT-CI
  script:
    - mvn verify -Dmaven.test.skip=true
