stages:
  - test

junit:
  stage: test
  image: "maven:3"
  # save mosquitto log to debug errors
  artifacts:
      when: on_failure
      paths:
        - mosquitto.log
  tags: 
    - BP-TDGT-CI
  script:
    - apt update && apt install -y mosquitto
    - cp ./mosquitto/* /mosquitto/config/
    - $(which mosquitto) -p 1883 > mosquitto.log 2>&1 &
    # config assumes broker is running on same machine as System under Test, so we need this environment for the tests
    - echo "127.0.0.1 users" >> /etc/hosts
    - mvn test

spotbugs:
  stage: test
  image: "maven:3"
  artifacts:
    when: on_failure
    paths:
      - target/site/*
  tags:
    - BP-TDGT-CI
  script:
    - mvn compile site
    - mvn verify -Dmaven.test.skip=true
