stages:
  - test

junit:
  stage: test
  image: "maven:3"
  tags: 
    - BP-TDGT-CI
  script:
    - apt update && apt install -y mosquitto
    - echo "127.0.0.1 users" >> /etc/hosts
    - cat /etc/hosts
    - wget users
    - mvn test

spotbugs:
  stage: test
  image: "maven:3"
  artifacts:
    when: on_failure
    paths:
      - target/site/*
  tags:
    - BP-TDGT-CI
  script:
    - mvn compile site
    - mvn verify -Dmaven.test.skip=true
