
stages:
  - test
  - scan

include:
  - template: SAST.gitlab-ci.yml

variables:
  SCAN_KUBERNETES_MANIFESTS: "true"


test:
  stage: test
  image: "openjdk:13-alpine"
  # save mosquitto log to debug errors
  artifacts:
      paths:
        - mosquitto.log
        - ./m2/
  tags: 
    - BP-TDGT-CI
  script:
    - apk add maven mosquitto
    - mkdir -p /mosquitto/config/
    - cp ./Docker/mosquitto.conf /mosquitto/config/
    - $(which mosquitto) -c /mosquitto/config/mosquitto.conf > mosquitto.log 2>&1 &
    # config assumes broker is running on same machine as System under Test, so we need this environment for the tests
    - echo "127.0.0.1 mosquitto" >> /etc/hosts
    # use directory as expected by scan
    - mvn package -Dmaven.repo.local=./.m2/repository

spotbugs-sast:
  dependencies:
    - test
  script:
    - /analyzer run
  variables:
    MAVEN_REPO_PATH: ./.m2/repository
  tags:
    - BP-TDGT-CI
  artifacts:
    reports:
      sast: gl-sast-report.json