/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
/* Header for class de_hpi_tdgt_fibers_Fiber */

#ifndef _Included_de_hpi_tdgt_fibers_Fiber
#define _Included_de_hpi_tdgt_fibers_Fiber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hpi_tdgt_fibers_Fiber
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hpi_tdgt_fibers_Fiber_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
