apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdgf-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pdgf-storage
  local:
    path: /home/worldofjarcraft/pdgf
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${NODENAME}
