apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdgf-output-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: output-storage
  hostPath:
    path: /mnt/disk/vol6
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${NODENAME}
